/* ========================================
   lang/en.js — English translations
   lang v1.0
   To remove this language:
     1. Delete this file
     2. Remove <option value="en"> in index.html
   ======================================== */

window.LANG_EN = {

  /* --- Navigation --- */
  nav_services:    'Services',
  nav_portfolio:   'Portfolio',
  nav_calculator:  'Price calculator',
  nav_sketch:      'Submit sketch',
  nav_about:       'About us',
  nav_cta:         'Get a quote',

  /* --- Hero --- */
  hero_sub:        'Multicam 3000 · Gardermoen region',
  hero_h1:         'Precision <em>milling</em><br>to order',
  hero_desc:       'CNC machining for wood, aluminium and plastics. From sketch to finished product — fast, precise, delivered locally.',
  hero_btn1:       'Calculate quote',
  hero_btn2:       'View portfolio',

  /* --- Machine card --- */
  machine_tag:     'Machine',
  machine_name:    'Multicam 3000',
  spec_table:      'Table size',
  spec_z:          'Z travel',
  spec_speed:      'Speed',
  spec_spindle:    'Spindle',
  machine_mats:    'Materials',

  /* --- Services --- */
  services_label:  'What we do',
  services_h2:     'CNC services',
  svc1_h:          'Custom CNC milling',
  svc1_p:          'Targeted operations on the Multicam 3000. From one-off prototypes to small runs. Wood, MDF, aluminium and plastics.',
  svc2_h:          'Drawing support & CAM prep',
  svc2_p:          'We convert your sketch or idea into a machine file. We help with DXF, G-code and CAM settings — even for beginners.',
  svc3_h:          'Small delivery service',
  svc3_p:          'Local delivery in the Gardermoen region. Fast, flexible and personal — no large logistics overhead.',
  svc4_h:          'Standard milling work',
  svc4_p:          'Common operations such as profiling, engraving, edge milling and pocketing. Quick turnaround for standard jobs.',
  svc5_h:          'Custom work & prototyping',
  svc5_p:          'Unique parts for industry, interiors or product development. We think along from concept to finished product.',
  svc6_h:          'File check & optimisation',
  svc6_p:          'File ready but unsure? We check your DXF or STL for machinability and adjust where needed.',

  /* --- Portfolio --- */
  portfolio_label: 'Previous work',
  portfolio_h2:    'Portfolio',
  p1_h: 'Decorative wall panels',
  p1_p: 'Engraved MDF panels for a hospitality venue. Series of 12, unique pattern per panel.',
  p1_m: 'MDF · Engraving · Series',
  p2_h: 'Aluminium housing',
  p2_p: 'Custom housing for an industrial sensor unit. Tolerance ±0.1 mm, anodising-ready surface.',
  p2_m: 'Aluminium · Pocketing · Prototype',
  p3_h: 'Acrylic display stand',
  p3_p: 'Transparent stand for product presentation. Crystal-clear acrylic, clean cut edges.',
  p3_m: 'Acrylic · Profiling · Small series',
  p4_h: 'Wooden jigs',
  p4_p: 'Precision milling jigs for repeated production in carpentry. FSC plywood, 15 mm.',
  p4_m: 'Plywood · Contour · Custom',
  p5_h: 'Facade lettering',
  p5_p: '3D letters from PVC foam sheet for signage. 20 mm thick, sprayed in RAL colour.',
  p5_m: 'PVC foam · 3D milling · Signage',
  p6_h: 'Interior inlay work',
  p6_p: 'Decorative elements for a furniture maker — inlay patterns in oak to 0.5 mm accuracy.',
  p6_m: 'Oak · Inlay milling · Interior',

  /* --- Calculator --- */
  calc_label:      'Price estimate',
  calc_h2:         'Online price tool',
  calc_intro:      'Enter your job details and get an instant indicative price. No registration needed.',
  calc_mat:        'Material',
  calc_mat1:       'Wood / MDF',
  calc_mat2:       'Aluminium',
  calc_mat3:       'Plastics / acrylic',
  calc_width:      'Width (mm)',
  calc_length:     'Length (mm)',
  calc_thick:      'Material thickness (mm)',
  calc_op:         'Operation',
  calc_op1:        'Profiling / contour',
  calc_op2:        'Pocketing',
  calc_op3:        'Engraving',
  calc_op4:        '3D milling',
  calc_qty:        'Quantity',
  calc_del:        'Delivery',
  calc_del1:       'Self collection',
  calc_del2:       'Local delivery (Gardermoen region)',
  calc_draw:       'Drawing support needed?',
  calc_draw1:      'No, I will supply a ready file',
  calc_draw2:      'Yes — minor adjustment',
  calc_draw3:      'Yes — full drawing from sketch',
  price_title:     'Indicative price',
  price_mat:       'Material cost',
  price_machine:   'Machining time',
  price_setup:     'Setup & preparation',
  price_qty:       'Quantity',
  price_drawing:   'Drawing work',
  price_delivery:  'Delivery',
  price_total:     'Total estimate',
  price_vat:       'excl. VAT · indicative',
  price_note:      'Fill in all fields for an estimate. Final price after file check by our team.',
  price_cta:       'Request quote',

  /* --- Sketch upload --- */
  sketch_label:    'Submit sketch',
  sketch_h2:       'From idea to CNC file',
  sketch_intro:    'No technical drawing? No problem. Submit your sketch and our team will convert it into a machine file.',
  step1_h:         'Upload your sketch',
  step1_p:         'Photo, scan, PDF or hand-drawn — any format is welcome.',
  step2_h:         'We assess the job',
  step2_p:         'Within 24 h you receive feedback and a price estimate for the drawing work.',
  step3_h:         'Approval & production',
  step3_p:         'Once you approve the CAD file we start milling straight away.',
  step4_h:         'Coming soon: direct AI conversion',
  step4_p:         'We are working on automated sketch-to-DXF conversion. Available soon.',
  upload_zone:     'Drop your file here or click to upload',
  upload_types:    'JPG, PNG, PDF, DXF, SVG · max 20 MB',
  sketch_note:     'Notes on the sketch',
  sketch_ph:       'Describe material, dimensions, special requirements...',
  sketch_cta:      'Send sketch',

  /* --- About --- */
  about_label:     'About us',
  about_h2:        'Local precision,<br>personal service',
  about_p:         'Based in the Gardermoen region, serving both private customers and companies in manufacturing. We combine machine precision with personal involvement.',
  stat1_lbl:       'Multicam model',
  stat2_lbl:       'Accuracy',
  stat3_lbl:       'Materials',
  stat4_lbl:       'Response time',
  contact_title:   'Contact & location',
  c_address_lbl:   'Address',
  c_address_val:   'Gardermoen region, Norway',
  c_email_lbl:     'E-mail',
  c_phone_lbl:     'Phone',
  c_hours_lbl:     'Opening hours',
  c_hours_val:     'Mon–Fri 08:00–17:00',
  c_area_lbl:      'Delivery area',
  c_area_val:      'Gardermoen & surroundings',

  /* --- Roadmap --- */
  road_label:      'Upcoming',
  road_h2:         'Roadmap',
  r1_phase: 'Phase 1', r1_h: 'Define target audience',
  r1_p: 'Private or industrial? Analysis of demand in the Gardermoen region.',
  r1_s: 'Mapping',
  r2_phase: 'Phase 2', r2_h: 'Industrial market',
  r2_p: 'Reaching manufacturing companies near Gardermoen — logistics, aviation, construction & interiors.',
  r2_s: 'Research',
  r3_phase: 'Phase 3', r3_h: 'Custom catalogue',
  r3_p: 'Develop fixed custom concepts: idea packages with set prices for common custom work.',
  r3_s: 'Concept',
  r4_phase: 'Phase 4', r4_h: 'Standard services',
  r4_p: 'Standardised services with a direct price list — easy to order without a quote.',
  r4_s: 'Later',

  /* --- Footer --- */
  footer_sub:      'Multicam 3000 · Gardermoen region · Wood · Aluminium · Plastics',
  footer_copy:     '© 2025 CenC — All rights reserved',
};
