/* ========================================
   lang/nl.js — Nederlandse vertalingen
   lang v1.0
   Om deze taal te verwijderen:
     1. Verwijder dit bestand
     2. Verwijder <option value="nl"> in index.html
   ======================================== */

window.LANG_NL = {

  /* --- Navigatie --- */
  nav_services:    'Diensten',
  nav_portfolio:   'Portfolio',
  nav_calculator:  'Prijscalculator',
  nav_sketch:      'Schets aanleveren',
  nav_about:       'Over ons',
  nav_cta:         'Bereken prijs',

  /* --- Hero --- */
  hero_sub:        'Multicam 3000 · Gardemoen regio',
  hero_h1:         'Precisie-<em>frezen</em><br>op maat',
  hero_desc:       'CNC-bewerkingen voor hout, aluminium en kunststof. Van schets tot eindproduct — snel, nauwkeurig, lokaal bezorgd.',
  hero_btn1:       'Bereken offerte',
  hero_btn2:       'Bekijk portfolio',

  /* --- Machine card --- */
  machine_tag:     'Productieapparaat',
  machine_name:    'Multicam 3000',
  spec_table:      'Tafelafmeting',
  spec_z:          'Z-slag',
  spec_speed:      'Snelheid',
  spec_spindle:    'Spindel',
  machine_mats:    'Materialen',

  /* --- Diensten --- */
  services_label:  'Wat wij doen',
  services_h2:     'CNC-diensten & services',
  svc1_h:          'CNC-frezen op maat',
  svc1_p:          'Gerichte bewerkingen op de Multicam 3000. Van enkelstuks prototypes tot kleine series. Hout, MDF, aluminium en kunststof.',
  svc2_h:          'Tekenhulp & CAM-voorbereiding',
  svc2_p:          'Jouw schets of idee omzetten naar een machinaal bestand. Wij helpen bij DXF, G-code en CAM-instellingen — ook voor beginners.',
  svc3_h:          'Kleine bezorgservice',
  svc3_p:          'Lokale bezorging in de regio Gardemoen. Snel, flexibel en persoonlijk — geen grote logistieke overhead.',
  svc4_h:          'Standaard freeswerk',
  svc4_p:          'Veelgevraagde bewerkingen zoals uitzagen, graveren, kantfrezen en pocketfrezen. Snelle doorlooptijd voor standaard klussen.',
  svc5_h:          'Maatwerk & prototyping',
  svc5_p:          'Unieke onderdelen voor industrie, interieur of productontwikkeling. Wij denken mee van concept tot klaar product.',
  svc6_h:          'Bestand-check & optimalisatie',
  svc6_p:          'Klaar bestand maar twijfels? Wij controleren jouw DXF of STL op freesbaarbaarheid en passen aan waar nodig.',

  /* --- Portfolio --- */
  portfolio_label: 'Eerder werk',
  portfolio_h2:    'Portfolio',
  p1_h: 'Decoratieve wandpanelen',
  p1_p: 'Gegraveerde MDF-panelen voor een horecagelegenheid. Serie van 12 stuks, uniek patroon per paneel.',
  p1_m: 'MDF · Graveren · Serie',
  p2_h: 'Aluminium behuizing',
  p2_p: 'Maatwerk behuizing voor industriële sensor-unit. Tolerantie ±0.1mm, anodiseerklaar oppervlak.',
  p2_m: 'Aluminium · Pocketfrezen · Prototype',
  p3_h: 'Acryl display-standaard',
  p3_p: 'Transparante standaard voor productpresentatie. Laserhelder acryl, strakke snijkanten.',
  p3_m: 'Acryl · Uitsnijden · Klein-serie',
  p4_h: 'Houten zaagmallen',
  p4_p: 'Nauwkeurige freesmallen voor herhaalde productie in timmerwerk. FSC multiplex, 15mm.',
  p4_m: 'Multiplex · Contourfrees · Maatwerk',
  p5_h: 'Gevellettering',
  p5_p: '3D-letters uit PVC-schuimplaat voor gevelreclame. Dikte 20mm, gespoten in RAL-kleur.',
  p5_m: 'PVC-foam · 3D-frees · Reclame',
  p6_h: 'Interieur inlegwerk',
  p6_p: 'Sierelementen voor een meubelmaker — inlegpatronen in eikenhout op 0.5mm nauwkeurig.',
  p6_m: 'Eiken · Inlegfrees · Interieur',

  /* --- Calculator --- */
  calc_label:      'Prijsindicatie',
  calc_h2:         'Online rekentool',
  calc_intro:      'Geef je opdracht in en ontvang direct een indicatieve prijs. Geen registratie nodig.',
  calc_mat:        'Materiaal',
  calc_mat1:       'Hout / MDF',
  calc_mat2:       'Aluminium',
  calc_mat3:       'Kunststof / acryl',
  calc_width:      'Breedte (mm)',
  calc_length:     'Lengte (mm)',
  calc_thick:      'Dikte materiaal (mm)',
  calc_op:         'Bewerking',
  calc_op1:        'Uitsnijden / contour',
  calc_op2:        'Pocketfrezen',
  calc_op3:        'Graveren',
  calc_op4:        '3D-frezen',
  calc_qty:        'Aantal stuks',
  calc_del:        'Bezorging',
  calc_del1:       'Zelf ophalen',
  calc_del2:       'Lokale bezorging (regio Gardemoen)',
  calc_draw:       'Extra: tekenhulp nodig?',
  calc_draw1:      'Nee, ik lever een klaar bestand aan',
  calc_draw2:      'Ja — eenvoudige aanpassing',
  calc_draw3:      'Ja — volledig tekenen vanaf schets',
  price_title:     'Indicatieve prijs',
  price_mat:       'Materiaalkosten',
  price_machine:   'Bewerkingstijd',
  price_setup:     'Setup & voorbereiding',
  price_qty:       'Stuks',
  price_drawing:   'Tekenwerkzaamheden',
  price_delivery:  'Bezorging',
  price_total:     'Totaal indicatie',
  price_vat:       'excl. BTW · indicatief',
  price_note:      'Vul alle velden in voor een indicatie. Definitieve prijs na bestandscheck door ons team.',
  price_cta:       'Offerte aanvragen',

  /* --- Schets upload --- */
  sketch_label:    'Schets aanleveren',
  sketch_h2:       'Van idee naar CNC-bestand',
  sketch_intro:    'Geen technische tekening? Geen probleem. Lever jouw schets in en ons team converteert deze naar een machinaal bestand.',
  step1_h:         'Upload jouw schets',
  step1_p:         'Foto, scan, PDF of handtekening — elk formaat is welkom.',
  step2_h:         'Wij beoordelen de opdracht',
  step2_p:         'Binnen 24u krijg je terugkoppeling en een prijsindicatie voor de tekenwerkzaamheden.',
  step3_h:         'Goedkeuring & productie',
  step3_p:         'Na jouw akkoord op het CAD-bestand starten wij direct met frezen.',
  step4_h:         'Toekomstig: directe AI-conversie',
  step4_p:         'Wij werken aan geautomatiseerde schets-naar-DXF conversie. Binnenkort beschikbaar.',
  upload_zone:     'Sleep je bestand hierheen of klik om te uploaden',
  upload_types:    'JPG, PNG, PDF, DXF, SVG · max 20MB',
  sketch_note:     'Toelichting op de schets',
  sketch_ph:       'Beschrijf materiaal, afmetingen, bijzonderheden...',
  sketch_cta:      'Schets insturen',

  /* --- Over ons --- */
  about_label:     'Over ons',
  about_h2:        'Lokale precisie,<br>persoonlijk contact',
  about_p:         'Gevestigd in de regio Gardemoen, actief voor zowel particulieren als bedrijven in de maakindustrie. Wij combineren machinale precisie met persoonlijk meedenken.',
  stat1_lbl:       'Multicam model',
  stat2_lbl:       'Nauwkeurigheid',
  stat3_lbl:       'Materialen',
  stat4_lbl:       'Responstijd',
  contact_title:   'Contact & locatie',
  c_address_lbl:   'Adres',
  c_address_val:   'Regio Gardemoen, Noorwegen',
  c_email_lbl:     'E-mail',
  c_phone_lbl:     'Telefoon',
  c_hours_lbl:     'Openingstijden',
  c_hours_val:     'Ma–Vr 08:00–17:00',
  c_area_lbl:      'Bezorggebied',
  c_area_val:      'Gardemoen & omgeving',

  /* --- Roadmap --- */
  road_label:      'Op de planning',
  road_h2:         'Roadmap',
  r1_phase: 'Fase 1', r1_h: 'Doelgroep bepalen',
  r1_p: 'Particulier of industrieel? Analyse van de vraag rondom de Gardemoen-regio en omgeving.',
  r1_s: 'In kaart brengen',
  r2_phase: 'Fase 2', r2_h: 'Industriële markt',
  r2_p: 'Aanspreken van de maakindustrie rondom Gardemoen — logistiek, luchtvaart, bouw & interieur.',
  r2_s: 'Uitzoeken',
  r3_phase: 'Fase 3', r3_h: 'Maatwerk-catalogus',
  r3_p: 'Vaste maatwerk-concepten uitwerken: ideepakketten met vaste prijzen voor veelgevraagd maatwerk.',
  r3_s: 'Concept',
  r4_phase: 'Fase 4', r4_h: 'Standaard werkzaamheden',
  r4_p: 'Gestandaardiseerde diensten met directe prijslijst — eenvoudig bestelbaar zonder offerte.',
  r4_s: 'Later',

  /* --- Footer --- */
  footer_sub:      'Multicam 3000 · Gardemoen regio · Hout · Aluminium · Kunststof',
  footer_copy:     '© 2025 CenC — Alle rechten voorbehouden',
};
