/* ========================================
   lang/no.js — Norske oversettelser
   lang v1.0
   For å fjerne dette språket:
     1. Slett denne filen
     2. Fjern <option value="no"> i index.html
   ======================================== */

window.LANG_NO = {

  /* --- Navigasjon --- */
  nav_services:    'Tjenester',
  nav_portfolio:   'Portefølje',
  nav_calculator:  'Priskalkulator',
  nav_sketch:      'Send skisse',
  nav_about:       'Om oss',
  nav_cta:         'Beregn pris',

  /* --- Hero --- */
  hero_sub:        'Multicam 3000 · Gardermoen-regionen',
  hero_h1:         'Presisjons-<em>fresing</em><br>på bestilling',
  hero_desc:       'CNC-bearbeiding av tre, aluminium og plast. Fra skisse til ferdig produkt — raskt, nøyaktig, levert lokalt.',
  hero_btn1:       'Beregn tilbud',
  hero_btn2:       'Se portefølje',

  /* --- Maskin-kort --- */
  machine_tag:     'Produksjonsmaskin',
  machine_name:    'Multicam 3000',
  spec_table:      'Bordstørrelse',
  spec_z:          'Z-slag',
  spec_speed:      'Hastighet',
  spec_spindle:    'Spindel',
  machine_mats:    'Materialer',

  /* --- Tjenester --- */
  services_label:  'Hva vi gjør',
  services_h2:     'CNC-tjenester',
  svc1_h:          'Skreddersydd CNC-fresing',
  svc1_p:          'Målrettede operasjoner på Multicam 3000. Fra enkeltprototyper til småserier. Tre, MDF, aluminium og plast.',
  svc2_h:          'Tegningshjelp & CAM-forberedelse',
  svc2_p:          'Vi konverterer skissen eller ideen din til en maskinfil. Vi hjelper med DXF, G-kode og CAM-innstillinger — også for nybegynnere.',
  svc3_h:          'Liten leveringstjeneste',
  svc3_p:          'Lokal levering i Gardermoen-regionen. Raskt, fleksibelt og personlig — ingen stor logistikkoverhead.',
  svc4_h:          'Standard fresing',
  svc4_p:          'Vanlige operasjoner som profilering, gravering, kanttfresing og lomme-fresing. Rask gjennomløpstid for standardjobber.',
  svc5_h:          'Skreddersydd arbeid & prototyping',
  svc5_p:          'Unike deler for industri, interiør eller produktutvikling. Vi tenker med fra konsept til ferdig produkt.',
  svc6_h:          'Filkontroll & optimalisering',
  svc6_p:          'Fil klar men usikker? Vi sjekker DXF- eller STL-filen din for maskinbarhet og justerer der det trengs.',

  /* --- Portefølje --- */
  portfolio_label: 'Tidligere arbeid',
  portfolio_h2:    'Portefølje',
  p1_h: 'Dekorative vegpaneler',
  p1_p: 'Graverte MDF-paneler for en serveringsvirksomhet. Serie på 12 stykker, unikt mønster per panel.',
  p1_m: 'MDF · Gravering · Serie',
  p2_h: 'Aluminiumskabinett',
  p2_p: 'Skreddersydd kabinett for industriell sensorenhet. Toleranse ±0,1 mm, anodiseringsklart overflate.',
  p2_m: 'Aluminium · Lommefresing · Prototype',
  p3_h: 'Akryl-displaystativ',
  p3_p: 'Transparent stativ for produktpresentasjon. Krystallklart akryl, rene snittflater.',
  p3_m: 'Akryl · Profilering · Småserie',
  p4_h: 'Tremaler',
  p4_p: 'Presisjonsfresede maler for gjentatt produksjon i trearbeid. FSC-kryssfiner, 15 mm.',
  p4_m: 'Kryssfiner · Kontur · Skreddersydd',
  p5_h: 'Fasadebokstaver',
  p5_p: '3D-bokstaver av PVC-skumplate for skiltfremstilling. 20 mm tykkelse, lakkert i RAL-farge.',
  p5_m: 'PVC-skum · 3D-fresing · Skilting',
  p6_h: 'Interiørinnlegg',
  p6_p: 'Dekorative elementer for en møbelmaker — innleggsmønstre i eik med 0,5 mm nøyaktighet.',
  p6_m: 'Eik · Innleggsfresing · Interiør',

  /* --- Kalkulator --- */
  calc_label:      'Prisindikasjon',
  calc_h2:         'Online priskalkulator',
  calc_intro:      'Fyll inn jobbdetaljene og få en umiddelbar veiledende pris. Ingen registrering nødvendig.',
  calc_mat:        'Materiale',
  calc_mat1:       'Tre / MDF',
  calc_mat2:       'Aluminium',
  calc_mat3:       'Plast / akryl',
  calc_width:      'Bredde (mm)',
  calc_length:     'Lengde (mm)',
  calc_thick:      'Materialtykkelse (mm)',
  calc_op:         'Operasjon',
  calc_op1:        'Profilering / kontur',
  calc_op2:        'Lommefresing',
  calc_op3:        'Gravering',
  calc_op4:        '3D-fresing',
  calc_qty:        'Antall',
  calc_del:        'Levering',
  calc_del1:       'Hentes selv',
  calc_del2:       'Lokal levering (Gardermoen-regionen)',
  calc_draw:       'Trenger du tegningshjelp?',
  calc_draw1:      'Nei, jeg leverer en ferdig fil',
  calc_draw2:      'Ja — mindre justering',
  calc_draw3:      'Ja — full tegning fra skisse',
  price_title:     'Veiledende pris',
  price_mat:       'Materialkostnad',
  price_machine:   'Maskineringstid',
  price_setup:     'Oppsett & forberedelse',
  price_qty:       'Antall',
  price_drawing:   'Tegningsarbeid',
  price_delivery:  'Levering',
  price_total:     'Totalt estimat',
  price_vat:       'ekskl. MVA · veiledende',
  price_note:      'Fyll inn alle felt for et estimat. Endelig pris etter filkontroll av teamet vårt.',
  price_cta:       'Be om tilbud',

  /* --- Skisse-opplasting --- */
  sketch_label:    'Send skisse',
  sketch_h2:       'Fra idé til CNC-fil',
  sketch_intro:    'Ingen teknisk tegning? Ikke noe problem. Send inn skissen din så konverterer teamet vårt den til en maskinfil.',
  step1_h:         'Last opp skissen din',
  step1_p:         'Foto, skanning, PDF eller håndtegning — alle formater er velkomne.',
  step2_h:         'Vi vurderer jobben',
  step2_p:         'Innen 24 t mottar du tilbakemelding og et prisestimat for tegningsarbeidet.',
  step3_h:         'Godkjenning & produksjon',
  step3_p:         'Etter at du har godkjent CAD-filen starter vi fresingen umiddelbart.',
  step4_h:         'Kommer snart: direkte AI-konvertering',
  step4_p:         'Vi jobber med automatisert skisse-til-DXF-konvertering. Tilgjengelig snart.',
  upload_zone:     'Slipp filen her eller klikk for å laste opp',
  upload_types:    'JPG, PNG, PDF, DXF, SVG · maks 20 MB',
  sketch_note:     'Kommentarer til skissen',
  sketch_ph:       'Beskriv materiale, mål, spesielle krav...',
  sketch_cta:      'Send skisse',

  /* --- Om oss --- */
  about_label:     'Om oss',
  about_h2:        'Lokal presisjon,<br>personlig service',
  about_p:         'Basert i Gardermoen-regionen, betjener både privatpersoner og bedrifter i produksjonsindustrien. Vi kombinerer maskinell presisjon med personlig engasjement.',
  stat1_lbl:       'Multicam-modell',
  stat2_lbl:       'Nøyaktighet',
  stat3_lbl:       'Materialer',
  stat4_lbl:       'Responstid',
  contact_title:   'Kontakt & beliggenhet',
  c_address_lbl:   'Adresse',
  c_address_val:   'Gardermoen-regionen, Norge',
  c_email_lbl:     'E-post',
  c_phone_lbl:     'Telefon',
  c_hours_lbl:     'Åpningstider',
  c_hours_val:     'Man–Fre 08:00–17:00',
  c_area_lbl:      'Leveringsområde',
  c_area_val:      'Gardermoen & omegn',

  /* --- Veikart --- */
  road_label:      'Kommende',
  road_h2:         'Veikart',
  r1_phase: 'Fase 1', r1_h: 'Definer målgruppe',
  r1_p: 'Privat eller industriell? Analyse av etterspørselen i Gardermoen-regionen.',
  r1_s: 'Kartlegges',
  r2_phase: 'Fase 2', r2_h: 'Industrielt marked',
  r2_p: 'Nå produksjonsbedrifter nær Gardermoen — logistikk, luftfart, bygg & interiør.',
  r2_s: 'Undersøkes',
  r3_phase: 'Fase 3', r3_h: 'Skreddersydd katalog',
  r3_p: 'Utvikle faste konsepter: idépakker med faste priser for vanlig skreddersydd arbeid.',
  r3_s: 'Konsept',
  r4_phase: 'Fase 4', r4_h: 'Standardtjenester',
  r4_p: 'Standardiserte tjenester med direkte prisliste — enkelt å bestille uten tilbud.',
  r4_s: 'Senere',

  /* --- Bunntekst --- */
  footer_sub:      'Multicam 3000 · Gardermoen-regionen · Tre · Aluminium · Plast',
  footer_copy:     '© 2025 CenC — Alle rettigheter forbeholdt',
};
